#!/usr/bin/env python3
"""Check the primitive one-psi Koszul homology complex used in main.tex.

For fixed bidegree (k, l), the primitive single-trace calculation is the middle
homology of

    C2(k,l) -> C1(k,l) -> C0(k,l),

where C1 is spanned by words with k x's and l y's, C0 is spanned by necklaces
with k+1 x's and l+1 y's, and C2 is spanned by two-psi words whose two gaps
have total bidegree (k-1,l-1).  The script verifies over Q that
ker(d1)/im(d2) is one-dimensional and generated by the total symmetrisation.
It also checks the open Hamiltonian action on these primitive descendants and
the closed coadjoint action formula on Taylor-dual monomials.
"""

from __future__ import annotations

from fractions import Fraction


def words(k: int, l: int) -> list[str]:
    out: list[str] = []

    def rec(a: int, b: int, prefix: str) -> None:
        if a == 0 and b == 0:
            out.append(prefix)
            return
        if a:
            rec(a - 1, b, prefix + "x")
        if b:
            rec(a, b - 1, prefix + "y")

    rec(k, l, "")
    return out


def necklace(word: str) -> str:
    if not word:
        return ""
    return min(word[i:] + word[:i] for i in range(len(word)))


def rank(matrix: list[list[int | Fraction]]) -> int:
    if not matrix or not matrix[0]:
        return 0
    a = [[Fraction(x) for x in row] for row in matrix]
    rows = len(a)
    cols = len(a[0])
    r = 0
    c = 0
    while r < rows and c < cols:
        pivot = None
        for i in range(r, rows):
            if a[i][c]:
                pivot = i
                break
        if pivot is None:
            c += 1
            continue
        a[r], a[pivot] = a[pivot], a[r]
        pv = a[r][c]
        a[r] = [x / pv for x in a[r]]
        for i in range(rows):
            if i != r and a[i][c]:
                factor = a[i][c]
                a[i] = [a[i][j] - factor * a[r][j] for j in range(cols)]
        r += 1
        c += 1
    return r


def mat_vec(matrix: list[list[int]], vector: list[int]) -> list[int]:
    return [sum(row[j] * vector[j] for j in range(len(vector))) for row in matrix]


def d1_matrix(k: int, l: int, w_basis: list[str], n_basis: list[str]) -> list[list[int]]:
    n_index = {n: i for i, n in enumerate(n_basis)}
    w_index = {w: i for i, w in enumerate(w_basis)}
    matrix = [[0 for _ in w_basis] for _ in n_basis]
    for w in w_basis:
        col = w_index[w]
        matrix[n_index[necklace("xy" + w)]][col] += 1
        matrix[n_index[necklace("yx" + w)]][col] -= 1
    return matrix


def d2_columns(k: int, l: int, w_basis: list[str]) -> list[list[int]]:
    if k == 0 or l == 0:
        return []
    w_index = {w: i for i, w in enumerate(w_basis)}
    cols: list[list[int]] = []
    for ku in range(k):
        for lu in range(l):
            for u in words(ku, lu):
                for v in words(k - 1 - ku, l - 1 - lu):
                    col = [0 for _ in w_basis]
                    for term, coeff in (
                        (v + "xy" + u, 1),
                        (v + "yx" + u, -1),
                        (u + "xy" + v, -1),
                        (u + "yx" + v, 1),
                    ):
                        col[w_index[term]] += coeff
                    cols.append(col)
    return cols


def columns_to_rows(cols: list[list[int]], row_count: int) -> list[list[int]]:
    return [[col[i] for col in cols] for i in range(row_count)]


def cyclic_derivative(trace_word: str, letter: str) -> list[str]:
    return [
        trace_word[i + 1 :] + trace_word[:i]
        for i, ch in enumerate(trace_word)
        if ch == letter
    ]


def one_psi_tail(trace_word: str) -> str:
    pos = trace_word.index("s")
    return trace_word[pos + 1 :] + trace_word[:pos]


def bracket_with_descendant(
    ham_k: int,
    ham_l: int,
    desc_k: int,
    desc_l: int,
    target_basis: list[str],
) -> list[int]:
    """Return {Tr(x^ham_k y^ham_l), Psi_{desc_k,desc_l}} in the target C1 basis."""
    target_index = {w: i for i, w in enumerate(target_basis)}
    out = [0 for _ in target_basis]
    f_word = "x" * ham_k + "y" * ham_l
    dfx = cyclic_derivative(f_word, "x")
    dfy = cyclic_derivative(f_word, "y")
    for w in words(desc_k, desc_l):
        g_word = "s" + w
        dgx = cyclic_derivative(g_word, "x")
        dgy = cyclic_derivative(g_word, "y")
        for left in dfx:
            for right in dgy:
                out[target_index[one_psi_tail(left + right)]] += 1
        for left in dfy:
            for right in dgx:
                out[target_index[one_psi_tail(left + right)]] -= 1
    return out


def in_span(cols: list[list[int]], vector: list[Fraction]) -> bool:
    if not cols:
        return all(x == 0 for x in vector)
    row_count = len(vector)
    base = columns_to_rows(cols, row_count)
    with_vector = columns_to_rows(cols + [vector], row_count)
    return rank(base) == rank(with_vector)


def check_bidegree(k: int, l: int) -> tuple[int, int, int]:
    w_basis = words(k, l)
    n_basis = sorted({necklace(w) for w in words(k + 1, l + 1)})
    d1 = d1_matrix(k, l, w_basis, n_basis)
    d2_cols = d2_columns(k, l, w_basis)

    for col in d2_cols:
        assert mat_vec(d1, col) == [0 for _ in n_basis], (k, l, "d1 d2 != 0")

    rank_d1 = rank(d1)
    ker_dim = len(w_basis) - rank_d1
    d2_rows = columns_to_rows(d2_cols, len(w_basis))
    rank_d2 = rank(d2_rows) if d2_cols else 0
    hom_dim = ker_dim - rank_d2

    psi = [1 for _ in w_basis]
    assert mat_vec(d1, psi) == [0 for _ in n_basis], (k, l, "Psi is not closed")
    rank_with_psi = rank(columns_to_rows(d2_cols + [psi], len(w_basis)))
    assert rank_with_psi == rank_d2 + 1, (k, l, "Psi is a boundary")
    assert hom_dim == 1, (k, l, hom_dim)
    return len(w_basis), len(n_basis), rank_d2


def check_descendant_action(max_exp: int) -> int:
    checked = 0
    for ham_k in range(max_exp + 1):
        for ham_l in range(max_exp + 1):
            if ham_k + ham_l == 0:
                continue
            for desc_k in range(max_exp + 1):
                for desc_l in range(max_exp + 1):
                    target_k = desc_k + ham_k - 1
                    target_l = desc_l + ham_l - 1
                    coefficient = ham_k * desc_l - ham_l * desc_k
                    if target_k < 0 or target_l < 0:
                        assert coefficient == 0
                        checked += 1
                        continue
                    target_basis = words(target_k, target_l)
                    bracket = bracket_with_descendant(
                        ham_k, ham_l, desc_k, desc_l, target_basis
                    )
                    d1 = d1_matrix(
                        target_k,
                        target_l,
                        target_basis,
                        sorted({necklace(w) for w in words(target_k + 1, target_l + 1)}),
                    )
                    assert mat_vec(d1, bracket) == [0 for _ in d1], (
                        ham_k,
                        ham_l,
                        desc_k,
                        desc_l,
                        "bracket not closed",
                    )
                    source_count = len(words(desc_k, desc_l))
                    target_count = len(target_basis)
                    scale = Fraction(coefficient * source_count, target_count)
                    expected = [scale for _ in target_basis]
                    difference = [
                        Fraction(bracket[i]) - expected[i] for i in range(target_count)
                    ]
                    assert in_span(
                        d2_columns(target_k, target_l, target_basis), difference
                    ), (ham_k, ham_l, desc_k, desc_l, "wrong homology class")
                    checked += 1
    return checked


def coadjoint_action_actual(
    ham_k: int, ham_l: int, dual_k: int, dual_l: int, max_test_exp: int
) -> dict[tuple[int, int], int]:
    """Compute ad^*_{x^ham_k y^ham_l}(delta_{dual_k,dual_l}) on test monomials."""
    out: dict[tuple[int, int], int] = {}
    for test_k in range(max_test_exp + 1):
        for test_l in range(max_test_exp + 1):
            if test_k + test_l == 0:
                continue
            bracket_k = ham_k + test_k - 1
            bracket_l = ham_l + test_l - 1
            coefficient = ham_k * test_l - ham_l * test_k
            if bracket_k == dual_k and bracket_l == dual_l and coefficient:
                out[(test_k, test_l)] = -coefficient
    return out


def coadjoint_action_expected(
    ham_k: int, ham_l: int, dual_k: int, dual_l: int
) -> dict[tuple[int, int], int]:
    target_k = dual_k - ham_k + 1
    target_l = dual_l - ham_l + 1
    coefficient = -(ham_k * dual_l - ham_l * dual_k + ham_k - ham_l)
    if target_k < 0 or target_l < 0 or target_k + target_l == 0 or coefficient == 0:
        return {}
    return {(target_k, target_l): coefficient}


def check_coadjoint_formula(max_exp: int) -> int:
    checked = 0
    # The target index can be one larger than the displayed dual index.
    max_test_exp = max_exp + 1
    for ham_k in range(max_exp + 1):
        for ham_l in range(max_exp + 1):
            if ham_k + ham_l == 0:
                continue
            for dual_k in range(max_exp + 1):
                for dual_l in range(max_exp + 1):
                    if dual_k + dual_l == 0:
                        continue
                    actual = coadjoint_action_actual(
                        ham_k, ham_l, dual_k, dual_l, max_test_exp
                    )
                    expected = coadjoint_action_expected(
                        ham_k, ham_l, dual_k, dual_l
                    )
                    assert actual == expected, (
                        ham_k,
                        ham_l,
                        dual_k,
                        dual_l,
                        actual,
                        expected,
                    )
                    checked += 1
    return checked


def run() -> None:
    max_exp = 5
    checked = 0
    for k in range(max_exp + 1):
        for l in range(max_exp + 1):
            check_bidegree(k, l)
            checked += 1
    print(
        "checked primitive one-psi homology in "
        f"{checked} bidegrees with exponents <= {max_exp}"
    )
    action_checked = check_descendant_action(3)
    print(
        "checked open Hamiltonian action on primitive descendants in "
        f"{action_checked} cases with exponents <= 3"
    )
    coadjoint_checked = check_coadjoint_formula(5)
    print(
        "checked closed coadjoint Taylor-dual formula in "
        f"{coadjoint_checked} cases with exponents <= 5"
    )


if __name__ == "__main__":
    run()
