#!/usr/bin/env python3
"""Check the primitive one-psi Koszul homology complex used in main.tex.

For fixed bidegree (k, l), the primitive single-trace calculation is the middle
homology of

    C2(k,l) -> C1(k,l) -> C0(k,l),

where C1 is spanned by words with k x's and l y's, C0 is spanned by necklaces
with k+1 x's and l+1 y's, and C2 is the alternating two-psi quotient spanned
by unordered gap pairs whose total bidegree is (k-1,l-1).  The script verifies
over Q that ker(d1)/im(d2) is one-dimensional and generated by the total
symmetrisation. It also checks the open Hamiltonian action on these primitive
descendants, the closed coadjoint action formula on Taylor-dual monomials, and
the obstruction to identifying the polynomial one-psi sector with the quantum
Moyal coadjoint module.  The final checks verify the corrected reduced target:
the distributional principal-part module with the full Moyal coadjoint action.
"""

from __future__ import annotations

from fractions import Fraction
from math import comb, factorial


def words(k: int, l: int) -> list[str]:
    out: list[str] = []

    def rec(a: int, b: int, prefix: str) -> None:
        if a == 0 and b == 0:
            out.append(prefix)
            return
        if a:
            rec(a - 1, b, prefix + "x")
        if b:
            rec(a, b - 1, prefix + "y")

    rec(k, l, "")
    return out


def necklace(word: str) -> str:
    if not word:
        return ""
    return min(word[i:] + word[:i] for i in range(len(word)))


def rank(matrix: list[list[int | Fraction]]) -> int:
    if not matrix or not matrix[0]:
        return 0
    a = [[Fraction(x) for x in row] for row in matrix]
    rows = len(a)
    cols = len(a[0])
    r = 0
    c = 0
    while r < rows and c < cols:
        pivot = None
        for i in range(r, rows):
            if a[i][c]:
                pivot = i
                break
        if pivot is None:
            c += 1
            continue
        a[r], a[pivot] = a[pivot], a[r]
        pv = a[r][c]
        a[r] = [x / pv for x in a[r]]
        for i in range(rows):
            if i != r and a[i][c]:
                factor = a[i][c]
                a[i] = [a[i][j] - factor * a[r][j] for j in range(cols)]
        r += 1
        c += 1
    return r


def mat_vec(matrix: list[list[int]], vector: list[int]) -> list[int]:
    return [sum(row[j] * vector[j] for j in range(len(vector))) for row in matrix]


def d1_matrix(k: int, l: int, w_basis: list[str], n_basis: list[str]) -> list[list[int]]:
    n_index = {n: i for i, n in enumerate(n_basis)}
    w_index = {w: i for i, w in enumerate(w_basis)}
    matrix = [[0 for _ in w_basis] for _ in n_basis]
    for w in w_basis:
        col = w_index[w]
        matrix[n_index[necklace("xy" + w)]][col] += 1
        matrix[n_index[necklace("yx" + w)]][col] -= 1
    return matrix


def two_psi_basis(k: int, l: int) -> list[tuple[str, str]]:
    """Basis for Tr(psi u psi v), modulo (u, v) = -(v, u)."""
    if k == 0 or l == 0:
        return []
    pairs: list[tuple[str, str]] = []
    for ku in range(k):
        for lu in range(l):
            for u in words(ku, lu):
                for v in words(k - 1 - ku, l - 1 - lu):
                    if u < v:
                        pairs.append((u, v))
    return pairs


def d2_columns(k: int, l: int, w_basis: list[str]) -> list[list[int]]:
    w_index = {w: i for i, w in enumerate(w_basis)}
    cols: list[list[int]] = []
    for u, v in two_psi_basis(k, l):
        col = [0 for _ in w_basis]
        for term, coeff in (
            (v + "xy" + u, 1),
            (v + "yx" + u, -1),
            (u + "xy" + v, -1),
            (u + "yx" + v, 1),
        ):
            col[w_index[term]] += coeff
        cols.append(col)
    return cols


def columns_to_rows(cols: list[list[int]], row_count: int) -> list[list[int]]:
    return [[col[i] for col in cols] for i in range(row_count)]


def cyclic_derivative(trace_word: str, letter: str) -> list[str]:
    return [
        trace_word[i + 1 :] + trace_word[:i]
        for i, ch in enumerate(trace_word)
        if ch == letter
    ]


def one_psi_tail(trace_word: str) -> str:
    pos = trace_word.index("s")
    return trace_word[pos + 1 :] + trace_word[:pos]


def bracket_with_descendant(
    ham_k: int,
    ham_l: int,
    desc_k: int,
    desc_l: int,
    target_basis: list[str],
) -> list[int]:
    """Return {Tr(x^ham_k y^ham_l), Psi_{desc_k,desc_l}} in the target C1 basis."""
    target_index = {w: i for i, w in enumerate(target_basis)}
    out = [0 for _ in target_basis]
    f_word = "x" * ham_k + "y" * ham_l
    dfx = cyclic_derivative(f_word, "x")
    dfy = cyclic_derivative(f_word, "y")
    for w in words(desc_k, desc_l):
        g_word = "s" + w
        dgx = cyclic_derivative(g_word, "x")
        dgy = cyclic_derivative(g_word, "y")
        for left in dfx:
            for right in dgy:
                out[target_index[one_psi_tail(left + right)]] += 1
        for left in dfy:
            for right in dgx:
                out[target_index[one_psi_tail(left + right)]] -= 1
    return out


def in_span(cols: list[list[int]], vector: list[Fraction]) -> bool:
    if not cols:
        return all(x == 0 for x in vector)
    row_count = len(vector)
    base = columns_to_rows(cols, row_count)
    with_vector = columns_to_rows(cols + [vector], row_count)
    return rank(base) == rank(with_vector)


def check_bidegree(k: int, l: int) -> tuple[int, int, int]:
    w_basis = words(k, l)
    n_basis = sorted({necklace(w) for w in words(k + 1, l + 1)})
    d1 = d1_matrix(k, l, w_basis, n_basis)
    d2_cols = d2_columns(k, l, w_basis)

    for col in d2_cols:
        assert mat_vec(d1, col) == [0 for _ in n_basis], (k, l, "d1 d2 != 0")

    rank_d1 = rank(d1)
    ker_dim = len(w_basis) - rank_d1
    d2_rows = columns_to_rows(d2_cols, len(w_basis))
    rank_d2 = rank(d2_rows) if d2_cols else 0
    hom_dim = ker_dim - rank_d2

    psi = [1 for _ in w_basis]
    assert mat_vec(d1, psi) == [0 for _ in n_basis], (k, l, "Psi is not closed")
    rank_with_psi = rank(columns_to_rows(d2_cols + [psi], len(w_basis)))
    assert rank_with_psi == rank_d2 + 1, (
        k,
        l,
        "Psi is not independent modulo boundaries",
    )
    assert hom_dim == 1, (k, l, hom_dim)
    return len(w_basis), len(n_basis), rank_d2


def check_descendant_action(max_exp: int) -> int:
    checked = 0
    for ham_k in range(max_exp + 1):
        for ham_l in range(max_exp + 1):
            if ham_k + ham_l == 0:
                continue
            for desc_k in range(max_exp + 1):
                for desc_l in range(max_exp + 1):
                    target_k = desc_k + ham_k - 1
                    target_l = desc_l + ham_l - 1
                    coefficient = ham_k * desc_l - ham_l * desc_k
                    if target_k < 0 or target_l < 0:
                        assert coefficient == 0
                        checked += 1
                        continue
                    target_basis = words(target_k, target_l)
                    bracket = bracket_with_descendant(
                        ham_k, ham_l, desc_k, desc_l, target_basis
                    )
                    d1 = d1_matrix(
                        target_k,
                        target_l,
                        target_basis,
                        sorted({necklace(w) for w in words(target_k + 1, target_l + 1)}),
                    )
                    assert mat_vec(d1, bracket) == [0 for _ in d1], (
                        ham_k,
                        ham_l,
                        desc_k,
                        desc_l,
                        "bracket not closed",
                    )
                    source_count = len(words(desc_k, desc_l))
                    target_count = len(target_basis)
                    scale = Fraction(coefficient * source_count, target_count)
                    expected = [scale for _ in target_basis]
                    difference = [
                        Fraction(bracket[i]) - expected[i] for i in range(target_count)
                    ]
                    assert in_span(
                        d2_columns(target_k, target_l, target_basis), difference
                    ), (ham_k, ham_l, desc_k, desc_l, "wrong homology class")
                    checked += 1
    return checked


def coadjoint_action_actual(
    ham_k: int, ham_l: int, dual_k: int, dual_l: int, max_test_exp: int
) -> dict[tuple[int, int], int]:
    """Compute ad^*_{x^ham_k y^ham_l}(delta_{dual_k,dual_l}) on test monomials."""
    out: dict[tuple[int, int], int] = {}
    for test_k in range(max_test_exp + 1):
        for test_l in range(max_test_exp + 1):
            if test_k + test_l == 0:
                continue
            bracket_k = ham_k + test_k - 1
            bracket_l = ham_l + test_l - 1
            coefficient = ham_k * test_l - ham_l * test_k
            if bracket_k == dual_k and bracket_l == dual_l and coefficient:
                out[(test_k, test_l)] = -coefficient
    return out


def coadjoint_action_expected(
    ham_k: int, ham_l: int, dual_k: int, dual_l: int
) -> dict[tuple[int, int], int]:
    target_k = dual_k - ham_k + 1
    target_l = dual_l - ham_l + 1
    coefficient = -(ham_k * dual_l - ham_l * dual_k + ham_k - ham_l)
    if target_k < 0 or target_l < 0 or target_k + target_l == 0 or coefficient == 0:
        return {}
    return {(target_k, target_l): coefficient}


def check_coadjoint_formula(max_exp: int) -> int:
    checked = 0
    # The target index can be one larger than the displayed dual index.
    max_test_exp = max_exp + 1
    for ham_k in range(max_exp + 1):
        for ham_l in range(max_exp + 1):
            if ham_k + ham_l == 0:
                continue
            for dual_k in range(max_exp + 1):
                for dual_l in range(max_exp + 1):
                    if dual_k + dual_l == 0:
                        continue
                    actual = coadjoint_action_actual(
                        ham_k, ham_l, dual_k, dual_l, max_test_exp
                    )
                    expected = coadjoint_action_expected(
                        ham_k, ham_l, dual_k, dual_l
                    )
                    assert actual == expected, (
                        ham_k,
                        ham_l,
                        dual_k,
                        dual_l,
                        actual,
                        expected,
                    )
                    checked += 1
    return checked


def principal_part_action_expected(
    ham_k: int, ham_l: int, pole_k: int, pole_l: int
) -> dict[tuple[int, int], int]:
    """Compute {x^ham_k y^ham_l, x^-pole_k-1 y^-pole_l-1 dx dy}_pp."""
    target_k = pole_k - ham_k + 1
    target_l = pole_l - ham_l + 1
    coefficient = -(ham_k * pole_l - ham_l * pole_k + ham_k - ham_l)
    if target_k < 0 or target_l < 0 or target_k + target_l == 0 or coefficient == 0:
        return {}
    return {(target_k, target_l): coefficient}


def check_principal_part_formula(max_exp: int) -> int:
    checked = 0
    for ham_k in range(max_exp + 1):
        for ham_l in range(max_exp + 1):
            if ham_k + ham_l == 0:
                continue
            for pole_k in range(max_exp + 1):
                for pole_l in range(max_exp + 1):
                    if pole_k + pole_l == 0:
                        continue
                    assert principal_part_action_expected(
                        ham_k, ham_l, pole_k, pole_l
                    ) == coadjoint_action_expected(
                        ham_k, ham_l, pole_k, pole_l
                    ), (ham_k, ham_l, pole_k, pole_l)
                    checked += 1
    return checked


def falling(n: int, r: int) -> int:
    out = 1
    for i in range(r):
        out *= n - i
    return out


def p_power_monomial_coeff(
    ham_k: int, ham_l: int, test_k: int, test_l: int, order: int
) -> int:
    """Coefficient of P^order(z1^ham_k z2^ham_l, z1^test_k z2^test_l)."""
    coeff = 0
    for alpha in range(order + 1):
        if ham_k < order - alpha or ham_l < alpha:
            continue
        if test_k < alpha or test_l < order - alpha:
            continue
        coeff += (
            (-1) ** alpha
            * comb(order, alpha)
            * falling(ham_k, order - alpha)
            * falling(ham_l, alpha)
            * falling(test_k, alpha)
            * falling(test_l, order - alpha)
        )
    return coeff


def normalized_moyal_bracket_coeff(
    ham_k: int, ham_l: int, test_k: int, test_l: int, order: int
) -> Fraction:
    """Coefficient of hbar^(order-1) in hbar^{-1}[f,g]_* for odd order."""
    if order == 0 or order % 2 == 0:
        return Fraction(0)
    coeff = p_power_monomial_coeff(ham_k, ham_l, test_k, test_l, order)
    return Fraction(coeff, (2 ** (order - 1)) * factorial(order))


def moyal_coadjoint_action_truncated(
    ham_k: int,
    ham_l: int,
    dual_k: int,
    dual_l: int,
    max_order: int,
) -> dict[tuple[int, int, int], Fraction]:
    """ad^* for the Moyal Lie algebra, truncated at odd order <= max_order.

    The key is (target_k, target_l, hbar_power). The target indices name
    the Taylor-dual basis vector on which the functional is nonzero.
    """
    out: dict[tuple[int, int, int], Fraction] = {}
    for order in range(1, max_order + 1, 2):
        target_k = dual_k - ham_k + order
        target_l = dual_l - ham_l + order
        if target_k < 0 or target_l < 0 or target_k + target_l == 0:
            continue
        coeff = -normalized_moyal_bracket_coeff(
            ham_k, ham_l, target_k, target_l, order
        )
        if coeff:
            out[(target_k, target_l, order - 1)] = coeff
    return out


def pbw_descendant_action_relabelled(
    ham_k: int, ham_l: int, desc_k: int, desc_l: int
) -> dict[tuple[int, int, int], Fraction]:
    """Polynomial one-psi action, relabelled as if Psi_{a,b} were rho_{a,b}."""
    target_k = desc_k + ham_k - 1
    target_l = desc_l + ham_l - 1
    coeff = ham_k * desc_l - ham_l * desc_k
    if target_k < 0 or target_l < 0 or target_k + target_l == 0 or coeff == 0:
        return {}
    return {(target_k, target_l, 0): Fraction(coeff)}


def check_quantum_descendant_obstruction(
    max_exp: int, max_order: int
) -> tuple[int, int, int]:
    """Attack the naive quantum descendant lift by exact Moyal coadjoint action.

    The candidate under attack is the label map Psi_{a,b} -> rho_{a,b}.
    It would have to identify the polynomial PBW one-psi action with the
    Moyal coadjoint action. The sweep counts all mismatches and all cases
    where genuine higher Moyal terms appear in the coadjoint action.
    """
    checked = 0
    mismatches = 0
    higher_terms = 0
    for ham_k in range(max_exp + 1):
        for ham_l in range(max_exp + 1):
            if ham_k + ham_l == 0:
                continue
            for dual_k in range(max_exp + 1):
                for dual_l in range(max_exp + 1):
                    if dual_k + dual_l == 0:
                        continue
                    moyal = moyal_coadjoint_action_truncated(
                        ham_k, ham_l, dual_k, dual_l, max_order
                    )
                    pbw = pbw_descendant_action_relabelled(
                        ham_k, ham_l, dual_k, dual_l
                    )
                    if moyal != pbw:
                        mismatches += 1
                    if any(hbar_power > 0 for _, _, hbar_power in moyal):
                        higher_terms += 1
                    checked += 1

    counterexample = moyal_coadjoint_action_truncated(4, 0, 1, 1, 3)
    assert counterexample == {(0, 4, 2): Fraction(-24)}, counterexample
    pbw_counterexample = pbw_descendant_action_relabelled(4, 0, 1, 1)
    assert pbw_counterexample == {(4, 0, 0): Fraction(4)}, pbw_counterexample
    return checked, mismatches, higher_terms


def add_series_term(
    series: dict[tuple[int, int, int], Fraction],
    key: tuple[int, int, int],
    coeff: Fraction,
) -> None:
    if coeff == 0:
        return
    series[key] = series.get(key, Fraction(0)) + coeff
    if series[key] == 0:
        del series[key]


def moyal_bracket_series(
    f_k: int,
    f_l: int,
    g_k: int,
    g_l: int,
    max_order: int,
) -> dict[tuple[int, int, int], Fraction]:
    """Reduced Moyal bracket of two monomials as a finite hbar series."""
    out: dict[tuple[int, int, int], Fraction] = {}
    for order in range(1, max_order + 1, 2):
        target_k = f_k + g_k - order
        target_l = f_l + g_l - order
        if target_k < 0 or target_l < 0 or target_k + target_l == 0:
            continue
        coeff = normalized_moyal_bracket_coeff(f_k, f_l, g_k, g_l, order)
        add_series_term(out, (target_k, target_l, order - 1), coeff)
    return out


def moyal_action_on_dual_vector(
    hamiltonian: dict[tuple[int, int, int], Fraction],
    vector: dict[tuple[int, int, int], Fraction],
    max_order: int,
    max_hbar_power: int,
) -> dict[tuple[int, int, int], Fraction]:
    """Apply a Moyal Hamiltonian series to a principal-part vector series."""
    out: dict[tuple[int, int, int], Fraction] = {}
    for (ham_k, ham_l, ham_hbar), ham_coeff in hamiltonian.items():
        for (dual_k, dual_l, dual_hbar), dual_coeff in vector.items():
            action = moyal_coadjoint_action_truncated(
                ham_k, ham_l, dual_k, dual_l, max_order
            )
            for (target_k, target_l, action_hbar), action_coeff in action.items():
                hbar_power = ham_hbar + dual_hbar + action_hbar
                if hbar_power <= max_hbar_power:
                    add_series_term(
                        out,
                        (target_k, target_l, hbar_power),
                        ham_coeff * dual_coeff * action_coeff,
                    )
    return out


def subtract_series(
    left: dict[tuple[int, int, int], Fraction],
    right: dict[tuple[int, int, int], Fraction],
) -> dict[tuple[int, int, int], Fraction]:
    out = dict(left)
    for key, coeff in right.items():
        add_series_term(out, key, -coeff)
    return out


def check_moyal_coadjoint_representation(
    max_exp: int, max_order: int, max_hbar_power: int
) -> int:
    """Verify [ad^*_f, ad^*_g] = ad^*_{ {f,g}_h } on principal parts."""
    checked = 0
    monomials = [
        (k, l)
        for k in range(max_exp + 1)
        for l in range(max_exp + 1)
        if k + l > 0
    ]
    for f_k, f_l in monomials:
        f = {(f_k, f_l, 0): Fraction(1)}
        for g_k, g_l in monomials:
            g = {(g_k, g_l, 0): Fraction(1)}
            bracket = moyal_bracket_series(f_k, f_l, g_k, g_l, max_order)
            for dual_k, dual_l in monomials:
                basis = {(dual_k, dual_l, 0): Fraction(1)}
                fg = moyal_action_on_dual_vector(
                    f,
                    moyal_action_on_dual_vector(
                        g, basis, max_order, max_hbar_power
                    ),
                    max_order,
                    max_hbar_power,
                )
                gf = moyal_action_on_dual_vector(
                    g,
                    moyal_action_on_dual_vector(
                        f, basis, max_order, max_hbar_power
                    ),
                    max_order,
                    max_hbar_power,
                )
                left = subtract_series(fg, gf)
                right = moyal_action_on_dual_vector(
                    bracket, basis, max_order, max_hbar_power
                )
                assert left == right, (
                    f_k,
                    f_l,
                    g_k,
                    g_l,
                    dual_k,
                    dual_l,
                    left,
                    right,
                )
                checked += 1
    return checked


def check_no_hbar_deformation_of_label_projection(max_exp: int) -> int:
    """Check the mod-h obstruction for any deformation of Psi -> rho.

    Hbar corrections cannot change the hbar^0 equation.  If a deformed
    map has leading term Psi_{a,b} -> rho_{a,b}, then already the two
    linear Hamiltonians force contradictory leading terms.
    """
    checked = 0
    for dual_k in range(max_exp + 1):
        for dual_l in range(max_exp + 1):
            if dual_k + dual_l == 0:
                continue
            pbw_z1 = pbw_descendant_action_relabelled(1, 0, dual_k, dual_l)
            coadj_z1 = moyal_coadjoint_action_truncated(1, 0, dual_k, dual_l, 1)
            expected_z1 = {
                (dual_k, dual_l + 1, 0): Fraction(-(dual_l + 1))
            }
            assert coadj_z1 == expected_z1, (dual_k, dual_l, coadj_z1)
            assert pbw_z1 != coadj_z1, (dual_k, dual_l, pbw_z1, coadj_z1)
            checked += 1

            pbw_z2 = pbw_descendant_action_relabelled(0, 1, dual_k, dual_l)
            coadj_z2 = moyal_coadjoint_action_truncated(0, 1, dual_k, dual_l, 1)
            expected_z2 = {
                (dual_k + 1, dual_l, 0): Fraction(dual_k + 1)
            }
            assert coadj_z2 == expected_z2, (dual_k, dual_l, coadj_z2)
            assert pbw_z2 != coadj_z2, (dual_k, dual_l, pbw_z2, coadj_z2)
            checked += 1
    return checked


def run() -> None:
    max_exp = 5
    checked = 0
    for k in range(max_exp + 1):
        for l in range(max_exp + 1):
            check_bidegree(k, l)
            checked += 1
    print(
        "checked primitive one-psi homology in "
        f"{checked} bidegrees with exponents <= {max_exp}"
    )
    action_checked = check_descendant_action(3)
    print(
        "checked open Hamiltonian action on primitive descendants in "
        f"{action_checked} cases with exponents <= 3"
    )
    coadjoint_checked = check_coadjoint_formula(5)
    print(
        "checked closed coadjoint Taylor-dual formula in "
        f"{coadjoint_checked} cases with exponents <= 5"
    )
    principal_part_checked = check_principal_part_formula(5)
    print(
        "checked principal-part coadjoint realization in "
        f"{principal_part_checked} cases with exponents <= 5"
    )
    quantum_checked, quantum_mismatches, quantum_higher_terms = (
        check_quantum_descendant_obstruction(5, 5)
    )
    print(
        "attacked naive quantum descendant lift in "
        f"{quantum_checked} cases with exponents <= 5 and Moyal order <= 5: "
        f"{quantum_mismatches} PBW-vs-Moyal mismatches, "
        f"{quantum_higher_terms} cases with genuine higher Moyal coadjoint terms"
    )
    print(
        "explicit obstruction: ad^*_{z1^4}(delta_1,1) has "
        "-24 hbar^2 delta_0,4, while the polynomial one-psi action sends "
        "Psi_1,1 to 4 Psi_4,0"
    )
    target_checked = check_moyal_coadjoint_representation(3, 5, 4)
    print(
        "checked corrected Moyal principal-part coadjoint target in "
        f"{target_checked} representation identities with exponents <= 3, "
        "Moyal order <= 5, and hbar power <= 4"
    )
    no_deformation_checked = check_no_hbar_deformation_of_label_projection(5)
    print(
        "checked no h-adic deformation of the classical Psi->rho label "
        "projection at the linear-generator leading term in "
        f"{no_deformation_checked} tests with labels <= 5"
    )


if __name__ == "__main__":
    run()
