#!/usr/bin/env python3
"""Search for left moment-ideal primitives of the quantum shear defect.

This is an exact-arithmetic evidence harness for the all-N radial-parts /
Weyl-trace bottleneck.

For fixed N,a,b it constructs, inside the matrix Weyl algebra

    [X^i_j, Y^k_l] = hbar delta^i_l delta^k_j,

the defect

    E_{a,b,N} =
      sum_{j=0}^b Tr(Y^j X^a Y^{b-j})
      - J_N({z1^(a+1)/(a+1), z2^(b+1)}_hbar).

It then searches for coefficients A_ij such that

    E_{a,b,N} = sum_{i,j} A_ij (YX - XY + hbar N I)^i_j

in the left ideal generated by the quantum comoment matrix.

The script has two modes.  The first searches a small invariant ansatz
spanned by hbar^p Tr(W M), where W is a word in X,Y and M is the moment
matrix.  The second is a brute-force normal-monomial left-ideal solve at
fixed Weyl weight.  Both modes use rational Gaussian elimination.  Finite
rank tests are evidence only; they are not an all-N proof.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from fractions import Fraction
from itertools import combinations, product
from math import comb, factorial
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


Index = Tuple[int, Tuple[int, ...], Tuple[int, ...]]
Poly = Dict[Index, Fraction]


def falling(n: int, r: int) -> int:
    out = 1
    for k in range(r):
        out *= n - k
    return out


def frac_str(q: Fraction) -> str:
    if q.denominator == 1:
        return str(q.numerator)
    return f"{q.numerator}/{q.denominator}"


class MatrixWeyl:
    """Normal-ordered matrix Weyl algebra over Q[hbar].

    A monomial is represented as

        (hbar_power, X_counts, Y_counts),

    with all X generators placed before all Y generators.  X generators
    commute among themselves, Y generators commute among themselves, and
    right multiplication by an X generator performs the exact contractions

        Y^k_l X^i_j = X^i_j Y^k_l - hbar delta^i_l delta^k_j.
    """

    def __init__(self, n: int):
        self.n = n
        self.var_count = n * n
        self._zero_counts = (0,) * self.var_count
        self._moment_cache: Dict[Tuple[int, int], Poly] = {}
        self._entry_cache: Dict[Tuple[Tuple[str, ...], int, int], Poly] = {}
        self._trace_cache: Dict[Tuple[str, ...], Poly] = {}
        self._weyl_trace_cache: Dict[Tuple[int, int], Poly] = {}

    def vid(self, i: int, j: int) -> int:
        return i * self.n + j

    def decode(self, v: int) -> Tuple[int, int]:
        return divmod(v, self.n)

    def one(self, coeff: Fraction = Fraction(1), hbar_power: int = 0) -> Poly:
        if coeff == 0:
            return {}
        return {(hbar_power, self._zero_counts, self._zero_counts): coeff}

    def add(self, p: Poly, q: Poly) -> Poly:
        out = dict(p)
        for monomial, coeff in q.items():
            out[monomial] = out.get(monomial, Fraction(0)) + coeff
            if out[monomial] == 0:
                del out[monomial]
        return out

    def scale(self, coeff: Fraction, p: Poly) -> Poly:
        if coeff == 0:
            return {}
        return {monomial: coeff * value for monomial, value in p.items() if coeff * value}

    def shift_hbar(self, power: int, p: Poly) -> Poly:
        if power == 0:
            return dict(p)
        return {
            (hbar_power + power, xs, ys): coeff
            for (hbar_power, xs, ys), coeff in p.items()
        }

    def x(self, i: int, j: int) -> Poly:
        counts = [0] * self.var_count
        counts[self.vid(i, j)] = 1
        return {(0, tuple(counts), self._zero_counts): Fraction(1)}

    def y(self, i: int, j: int) -> Poly:
        counts = [0] * self.var_count
        counts[self.vid(i, j)] = 1
        return {(0, self._zero_counts, tuple(counts)): Fraction(1)}

    def commutator_constant(self, x_var: int, y_var: int) -> int:
        i, j = self.decode(x_var)
        k, l = self.decode(y_var)
        return 1 if i == l and k == j else 0

    def _right_mul_x_monomial(self, monomial: Index, coeff: Fraction, x_var: int) -> Poly:
        hbar_power, xs, ys = monomial
        out: Poly = {}

        new_xs = list(xs)
        new_xs[x_var] += 1
        out[(hbar_power, tuple(new_xs), ys)] = coeff

        for y_var, y_power in enumerate(ys):
            if y_power == 0:
                continue
            if not self.commutator_constant(x_var, y_var):
                continue
            new_ys = list(ys)
            new_ys[y_var] -= 1
            contracted = (hbar_power + 1, xs, tuple(new_ys))
            out[contracted] = out.get(contracted, Fraction(0)) - coeff * y_power

        return {mon: val for mon, val in out.items() if val}

    def _right_mul_y_monomial(self, monomial: Index, coeff: Fraction, y_var: int) -> Poly:
        hbar_power, xs, ys = monomial
        new_ys = list(ys)
        new_ys[y_var] += 1
        return {(hbar_power, xs, tuple(new_ys)): coeff}

    def mul_monomial(self, left: Index, left_coeff: Fraction, right: Index, right_coeff: Fraction) -> Poly:
        _, right_xs, right_ys = right
        out: Poly = {left: left_coeff * right_coeff}

        for x_var, multiplicity in enumerate(right_xs):
            for _ in range(multiplicity):
                next_out: Poly = {}
                for monomial, coeff in out.items():
                    for new_monomial, new_coeff in self._right_mul_x_monomial(
                        monomial, coeff, x_var
                    ).items():
                        next_out[new_monomial] = next_out.get(new_monomial, Fraction(0)) + new_coeff
                out = {monomial: coeff for monomial, coeff in next_out.items() if coeff}

        for y_var, multiplicity in enumerate(right_ys):
            for _ in range(multiplicity):
                next_out = {}
                for monomial, coeff in out.items():
                    for new_monomial, new_coeff in self._right_mul_y_monomial(
                        monomial, coeff, y_var
                    ).items():
                        next_out[new_monomial] = next_out.get(new_monomial, Fraction(0)) + new_coeff
                out = {monomial: coeff for monomial, coeff in next_out.items() if coeff}

        return out

    def mul(self, p: Poly, q: Poly) -> Poly:
        out: Poly = {}
        for left, left_coeff in p.items():
            for right, right_coeff in q.items():
                for monomial, coeff in self.mul_monomial(left, left_coeff, right, right_coeff).items():
                    out[monomial] = out.get(monomial, Fraction(0)) + coeff
        return {monomial: coeff for monomial, coeff in out.items() if coeff}

    def matrix_word_entry(self, word: Sequence[str], row: int, col: int) -> Poly:
        key = (tuple(word), row, col)
        if key in self._entry_cache:
            return dict(self._entry_cache[key])
        if not word:
            out = self.one(Fraction(1) if row == col else Fraction(0))
            self._entry_cache[key] = out
            return dict(out)

        out: Poly = {}
        for internal in product(range(self.n), repeat=len(word) - 1):
            indices = (row,) + internal + (col,)
            term = self.one()
            for pos, letter in enumerate(word):
                i = indices[pos]
                j = indices[pos + 1]
                term = self.mul(term, self.x(i, j) if letter == "X" else self.y(i, j))
            out = self.add(out, term)
        self._entry_cache[key] = out
        return dict(out)

    def trace_word(self, word: Sequence[str]) -> Poly:
        key = tuple(word)
        if key in self._trace_cache:
            return dict(self._trace_cache[key])
        if not word:
            out = self.one(Fraction(self.n))
            self._trace_cache[key] = out
            return dict(out)
        out: Poly = {}
        for i in range(self.n):
            out = self.add(out, self.matrix_word_entry(word, i, i))
        self._trace_cache[key] = out
        return dict(out)

    def weyl_trace_monomial(self, x_power: int, y_power: int) -> Poly:
        key = (x_power, y_power)
        if key in self._weyl_trace_cache:
            return dict(self._weyl_trace_cache[key])
        length = x_power + y_power
        if length == 0:
            out = self.one(Fraction(self.n))
            self._weyl_trace_cache[key] = out
            return dict(out)

        out: Poly = {}
        for x_positions in combinations(range(length), x_power):
            x_set = set(x_positions)
            word = tuple("X" if pos in x_set else "Y" for pos in range(length))
            out = self.add(out, self.trace_word(word))
        out = self.scale(Fraction(1, comb(length, x_power)), out)
        self._weyl_trace_cache[key] = out
        return dict(out)

    def moyal_bracket_trace(self, a: int, b: int) -> Poly:
        """J_N({z1^(a+1)/(a+1), z2^(b+1)}_hbar)."""
        out: Poly = {}
        max_order = min(a + 1, b + 1)
        for order in range(1, max_order + 1, 2):
            coeff = Fraction(
                falling(a + 1, order) * falling(b + 1, order),
                (a + 1) * (2 ** (order - 1)) * factorial(order),
            )
            term = self.weyl_trace_monomial(a + 1 - order, b + 1 - order)
            out = self.add(out, self.scale(coeff, self.shift_hbar(order - 1, term)))
        return out

    def shear_sum(self, a: int, b: int) -> Poly:
        out: Poly = {}
        for j in range(b + 1):
            word = tuple(["Y"] * j + ["X"] * a + ["Y"] * (b - j))
            out = self.add(out, self.trace_word(word))
        return out

    def shear_defect(self, a: int, b: int) -> Poly:
        return self.add(self.shear_sum(a, b), self.scale(Fraction(-1), self.moyal_bracket_trace(a, b)))

    def moment_entry(self, i: int, j: int) -> Poly:
        key = (i, j)
        if key in self._moment_cache:
            return dict(self._moment_cache[key])
        out: Poly = {}
        for k in range(self.n):
            out = self.add(out, self.mul(self.y(i, k), self.x(k, j)))
            out = self.add(out, self.scale(Fraction(-1), self.mul(self.x(i, k), self.y(k, j))))
        if i == j:
            out = self.add(out, self.one(Fraction(self.n), hbar_power=1))
        self._moment_cache[key] = out
        return dict(out)

    def trace_word_times_moment(self, word: Sequence[str]) -> Poly:
        """Return sum_{i,j} (word)^j_i M^i_j = Tr(word * M).

        This is a left-ideal element with coefficient
        A_ij = (word)^j_i.
        """
        out: Poly = {}
        for i in range(self.n):
            for j in range(self.n):
                coeff = self.matrix_word_entry(word, j, i)
                out = self.add(out, self.mul(coeff, self.moment_entry(i, j)))
        return out

    def left_monomial_times_moment(self, monomial: Index, i: int, j: int) -> Poly:
        return self.mul({monomial: Fraction(1)}, self.moment_entry(i, j))

    def format_monomial(self, monomial: Index) -> str:
        hbar_power, xs, ys = monomial
        pieces: List[str] = []
        if hbar_power:
            pieces.append("hbar" if hbar_power == 1 else f"hbar^{hbar_power}")
        for prefix, counts in (("X", xs), ("Y", ys)):
            for var, multiplicity in enumerate(counts):
                if multiplicity == 0:
                    continue
                i, j = self.decode(var)
                atom = f"{prefix}{i}{j}"
                pieces.extend([atom] * multiplicity)
        return "*".join(pieces) if pieces else "1"


def all_words(length: int) -> Iterable[Tuple[str, ...]]:
    for mask in range(1 << length):
        yield tuple("Y" if (mask >> bit) & 1 else "X" for bit in range(length))


def word_label(word: Sequence[str]) -> str:
    return "".join(word) if word else "I"


def weak_compositions(total: int, slots: int) -> Iterable[Tuple[int, ...]]:
    if slots == 1:
        yield (total,)
        return
    for value in range(total + 1):
        for tail in weak_compositions(total - value, slots - 1):
            yield (value,) + tail


def normal_monomials_of_weight(var_count: int, weight: int) -> Iterable[Index]:
    zero = (0,) * var_count
    for hbar_power in range(weight // 2 + 1):
        variable_degree = weight - 2 * hbar_power
        for counts in weak_compositions(variable_degree, 2 * var_count):
            xs = counts[:var_count]
            ys = counts[var_count:]
            if xs == zero and ys == zero and hbar_power == 0 and weight != 0:
                continue
            yield (hbar_power, xs, ys)


@dataclass(frozen=True)
class LinearSolution:
    consistent: bool
    coefficients: Dict[int, Fraction]
    rank: int
    row_count: int
    column_count: int


def solve_sparse(columns: Sequence[Poly], target: Poly) -> LinearSolution:
    keys = set(target)
    for column in columns:
        keys.update(column)
    ordered_keys = sorted(keys)

    rows: List[Tuple[Dict[int, Fraction], Fraction]] = []
    for key in ordered_keys:
        row: Dict[int, Fraction] = {}
        for col_index, column in enumerate(columns):
            value = column.get(key)
            if value:
                row[col_index] = value
        rhs = target.get(key, Fraction(0))
        if row or rhs:
            rows.append((row, rhs))

    pivot_cols: List[int] = []
    pivot_row = 0
    mutable_rows = [[dict(row), rhs] for row, rhs in rows]
    column_count = len(columns)

    for col in range(column_count):
        selected: Optional[int] = None
        for row_index in range(pivot_row, len(mutable_rows)):
            if mutable_rows[row_index][0].get(col):
                selected = row_index
                break
        if selected is None:
            continue

        mutable_rows[pivot_row], mutable_rows[selected] = (
            mutable_rows[selected],
            mutable_rows[pivot_row],
        )
        pivot = mutable_rows[pivot_row][0][col]
        inv_pivot = Fraction(1, 1) / pivot
        mutable_rows[pivot_row][0] = {
            key: value * inv_pivot for key, value in mutable_rows[pivot_row][0].items()
        }
        mutable_rows[pivot_row][1] *= inv_pivot

        for row_index in range(len(mutable_rows)):
            if row_index == pivot_row:
                continue
            factor = mutable_rows[row_index][0].get(col)
            if not factor:
                continue
            new_row = dict(mutable_rows[row_index][0])
            for key, value in mutable_rows[pivot_row][0].items():
                updated = new_row.get(key, Fraction(0)) - factor * value
                if updated:
                    new_row[key] = updated
                elif key in new_row:
                    del new_row[key]
            mutable_rows[row_index][0] = new_row
            mutable_rows[row_index][1] -= factor * mutable_rows[pivot_row][1]

        pivot_cols.append(col)
        pivot_row += 1
        if pivot_row == len(mutable_rows):
            break

    for row, rhs in mutable_rows:
        if not row and rhs:
            return LinearSolution(False, {}, len(pivot_cols), len(rows), column_count)

    coeffs: Dict[int, Fraction] = {}
    for row_index, col in enumerate(pivot_cols):
        rhs = mutable_rows[row_index][1]
        if rhs:
            coeffs[col] = rhs
    return LinearSolution(True, coeffs, len(pivot_cols), len(rows), column_count)


def poly_equal(p: Poly, q: Poly) -> bool:
    if len(p) != len(q):
        return False
    for key, value in p.items():
        if q.get(key, Fraction(0)) != value:
            return False
    return True


@dataclass(frozen=True)
class SearchResult:
    n: int
    a: int
    b: int
    defect_terms: int
    mode: str
    consistent: bool
    verified: bool
    rank: int
    rows: int
    columns: int
    support: List[Tuple[str, Fraction]]


def reconstruct(columns: Sequence[Poly], coeffs: Dict[int, Fraction], algebra: MatrixWeyl) -> Poly:
    out: Poly = {}
    for col_index, coeff in coeffs.items():
        out = algebra.add(out, algebra.scale(coeff, columns[col_index]))
    return out


def search_covariant(algebra: MatrixWeyl, a: int, b: int, target: Poly) -> SearchResult:
    weight = a + b - 2
    if weight < 0:
        columns: List[Poly] = []
        labels: List[str] = []
    else:
        columns = []
        labels = []
        for hbar_power in range(weight // 2 + 1):
            length = weight - 2 * hbar_power
            for word in all_words(length):
                column = algebra.shift_hbar(hbar_power, algebra.trace_word_times_moment(word))
                if not column:
                    continue
                prefix = "" if hbar_power == 0 else f"hbar^{hbar_power} "
                labels.append(f"{prefix}Tr({word_label(word)} M)")
                columns.append(column)

    solution = solve_sparse(columns, target)
    reconstructed = reconstruct(columns, solution.coefficients, algebra) if solution.consistent else {}
    support = [
        (labels[col_index], coeff)
        for col_index, coeff in sorted(solution.coefficients.items())
        if coeff
    ]
    return SearchResult(
        algebra.n,
        a,
        b,
        len(target),
        "covariant-trace",
        solution.consistent,
        solution.consistent and poly_equal(reconstructed, target),
        solution.rank,
        solution.row_count,
        solution.column_count,
        support,
    )


def search_generic(algebra: MatrixWeyl, a: int, b: int, target: Poly) -> SearchResult:
    weight = a + b - 2
    columns: List[Poly] = []
    labels: List[str] = []
    if weight >= 0:
        basis = list(normal_monomials_of_weight(algebra.var_count, weight))
        for i in range(algebra.n):
            for j in range(algebra.n):
                for monomial in basis:
                    column = algebra.left_monomial_times_moment(monomial, i, j)
                    if not column:
                        continue
                    labels.append(
                        f"A_{i}{j} += {algebra.format_monomial(monomial)}"
                    )
                    columns.append(column)

    solution = solve_sparse(columns, target)
    reconstructed = reconstruct(columns, solution.coefficients, algebra) if solution.consistent else {}
    support = [
        (labels[col_index], coeff)
        for col_index, coeff in sorted(solution.coefficients.items())
        if coeff
    ]
    return SearchResult(
        algebra.n,
        a,
        b,
        len(target),
        "generic-left",
        solution.consistent,
        solution.consistent and poly_equal(reconstructed, target),
        solution.rank,
        solution.row_count,
        solution.column_count,
        support,
    )


def run_case(n: int, a: int, b: int, use_generic: bool) -> SearchResult:
    algebra = MatrixWeyl(n)
    target = algebra.shear_defect(a, b)
    if not target:
        return SearchResult(n, a, b, 0, "zero-defect", True, True, 0, 0, 0, [])

    covariant = search_covariant(algebra, a, b, target)
    if covariant.consistent and covariant.verified:
        return covariant
    if not use_generic:
        return covariant
    return search_generic(algebra, a, b, target)


def parse_case(raw: str) -> Tuple[int, int, int]:
    parts = raw.split(",")
    if len(parts) != 3:
        raise argparse.ArgumentTypeError("case must have form N,a,b")
    try:
        n, a, b = (int(part) for part in parts)
    except ValueError as exc:
        raise argparse.ArgumentTypeError("case entries must be integers") from exc
    if n < 1 or a < 0 or b < 0:
        raise argparse.ArgumentTypeError("require N >= 1 and a,b >= 0")
    return n, a, b


def default_cases() -> List[Tuple[int, int, int]]:
    return [
        (2, 0, 0),
        (2, 1, 1),
        (2, 1, 2),
        (2, 2, 1),
        (2, 2, 2),
        (2, 2, 3),
        (2, 3, 2),
        (2, 3, 3),
        (2, 2, 4),
        (2, 4, 2),
        (2, 3, 4),
        (2, 4, 3),
        (2, 4, 4),
        (3, 1, 1),
        (3, 2, 2),
        (3, 2, 3),
        (3, 3, 2),
        (3, 3, 3),
        (4, 2, 2),
    ]


def print_result(result: SearchResult, max_terms: int) -> None:
    status = "PASS" if result.consistent and result.verified else "FAIL"
    print(
        f"{status} N={result.n} a={result.a} b={result.b} "
        f"mode={result.mode} defect_terms={result.defect_terms} "
        f"rank={result.rank} rows={result.rows} cols={result.columns} "
        f"support={len(result.support)}"
    )
    if not result.support:
        return
    if len(result.support) > max_terms:
        print(f"  support omitted: {len(result.support)} terms exceeds --max-terms={max_terms}")
        return
    for label, coeff in result.support:
        print(f"  {frac_str(coeff):>6} * {label}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--case",
        action="append",
        type=parse_case,
        help="case N,a,b. May be repeated. Defaults to a fixed low-rank window.",
    )
    parser.add_argument(
        "--no-generic",
        action="store_true",
        help="only try the covariant trace ansatz; do not run the brute-force left solve.",
    )
    parser.add_argument(
        "--max-terms",
        type=int,
        default=24,
        help="maximum primitive support terms printed per case.",
    )
    args = parser.parse_args()

    cases = args.case if args.case else default_cases()
    print("Quantum shear primitive search")
    print("normal order: all X entries before all Y entries")
    print("Weyl weight: deg(X)=deg(Y)=1, deg(hbar)=2")
    print("finite tests are evidence only, not an all-N proof")
    print()

    failed = 0
    for case in cases:
        result = run_case(*case, use_generic=not args.no_generic)
        print_result(result, args.max_terms)
        if not (result.consistent and result.verified):
            failed += 1

    print()
    if failed:
        print(f"FAIL: {failed} case(s) did not produce a verified primitive.")
        return 1
    print(f"PASS: {len(cases)} case(s) produced zero defects or verified primitives.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
